### ISSUE TITLE
Fix populate function in database.js

### ISSUE THREAD

**Issue by chrisakakay** [viveka-io/viveka#89]
"url: 'http://localhost:5555/dev-section/test-page.html#/' + testCase.textId,"

This should not be hardcoded!

**Comment by chrisakakay** [comment]
Depends on #82

**Comment by TWSgit** [comment]
This issue should handle the built-in test cases as well. Please create a gulp task or something to build/init those tests with baseline and 'modified' fingerprints too. (currently this functionality works on the diff page only :/)
